### ISSUE TITLE
Idee: Verwarnsystem einführen

### ISSUE THREAD

**Issue by pavl21** [antisocialtobi/BanSystem-v2#13]
Ich verwarne gern mal Spieler, wenn sie sich mal nicht an die Regeln halten. Aber derzeit kann man nur Spieler bannen. Eben Bansystem. Aber ein Verwarnsystem fände ich schon Sinnvoll.

**Comment by antisocialtobi** [comment]
Moin, Ich finde deinen Vorschlag nicht schlecht. Kannst du mir einen konkreteren Vorschlag machen wie du das gerne ungesetzt hättest. Z. B. die syntax oder ob man auf einen grund verwarnen kann oder nur generell und sowas. Mfg Tobi

**Comment by pavl21** [comment]
Im Grunde finde ich es wichtig, das jeder Server selbst entscheiden kann wie oft man Verwarnungen geben kann bis etwas passiert. Ich würde es wichtig und als Nachweis gut finden, das man einen Grund hinschreibt weswegen man verwarnt wurde. 

Sobald man jemanden verwarnt, sollten sowohl alle Spieler, die OP Rechte haben (bzw. die entsprechende Permission) informiert werden. Auch der Spieler um den es geht, derjenige sollte auch informiert werden, das er die Verwarnung X von X mit dem Grund ... erhalten hat. 

Spieler mit Verwarnungen sollen die Möglichkeit haben, einen Einspruch zu erheben. Admins oder Supporter können es auch fälschlicherweise vergeben haben. 


_Aufwendiger, aber vielleicht übersichtlicher:_ Eine Möglichkeit, das man einen Discord Webhook verknüpfen kann. Somit kann man in einem Channel alle Verwarnungen einsehen (bzw. alle Aktivitäten wie Kicken, Ban usw.) mit dem entsprechenden Grund. Quasi ein Log im Discord.

**Comment by antisocialtobi** [comment]
Danke dir für deinen Vorschlag, ich schau mal was ich machen kann.
Mfg Tobi
