### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by sluhtie** [antisocialtobi/BanSystem-v2#15]
Wäre es möglich vielleicht Velocity zu Supporten. Das wäre sehr hilfreich, da es keine Ban Systeme mit IDs für velocity gibt derzeit.

**Comment by antisocialtobi** [comment]
Ist in Arbeit. Mfg

**Comment by antisocialtobi** [comment]
Ist nun in der Release 3.0 Verfügbar.
